project:
  type: website
  output-dir: docs

website:
  title: "SCCDS Canvas"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged

editor: source

knitr:
  opts_chunk: 
    message: false
    warnings: false
    comment: "#>" 

