{
  "hash": "6070f16c99d3c847d8e3394005d0115b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Bootstrap Method\"\ndate-modified: \"2024-10-16\"\n---\n\n\n\nThe Boostrap Method is an approach that can construct the sampling distribution of several estimators, not all estimators, without imposing a mathematical model on the data. The idea is that the sample $X_1, \\ldots, X_n$ is generated from a distribution function called $F(\\theta)$. If the sample is large enough, then the empirical distribution function $\\hat F_n$ should begin to look like the true distribution function $F$. This implies that the sample contains all the information of $F$. Therefore, if we resample from our sample, with replacement, we are then sampling from our empirical distribution $\\hat F_n$, which looks really close to the true distribution function $F$.\n\n**R Packages Used**\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlibrary(tidyverse)\ntheme_set(theme_bw())\ntheme_update(axis.title = element_text(size = 24))\n```\n:::\n\n\n\n## Empirical Distribution Function\n\nThe empirical distribution function is designed to estimate a random variable's distribution function. For an observed sample $\\{x_i\\}^n_{i=1}$, the empirical distribution function is\n\n$$\n\\hat F_n(x) = \\left\\{\\begin{array}{cc}\n0, & x < x_{(1)} \\\\\n\\frac{i}{n},& x_{(i)} \\leq x <x_{(i+1)},\\ i = 1,\\ldots,n-1\\\\\n1,& x_{(n)}\\leq x\n\\end{array}\n\\right.\n$$\n\nwhere $x_{(1)}, \\ldots, x_{(n)}$ is the ordered sample. Looking at the Glivenko-Cantelli Theorem, the empirical distribution function converges to the true function as $n\\rightarrow \\infty$. For a large enough sample, $\\hat F_n$ will contain the same information as $F$.\n\n\n::: callout-note\n### Glivenko-Cantelli Theorem\n\nIf random variables $X_1, X_2, \\cdots, X_n$ are independent come from the same distribution ($iid$), then\n\n$$\n\\hat F_n (x) \\rightarrow F(x)\n$$\n\nconverges uniformly as $n\\rightarrow \\infty$, for more information click [here](https://en.wikipedia.org/wiki/Glivenko%E2%80%93Cantelli_theorem).\n\n:::\n\n\n\nAccordingly, the sample generated has it's own distribution function called $\\hat F_n$ where the probability of seeing any value $x_i$ is $1/n$. Therefore, if we were to resample $\\{x_i\\}^n_{i=1}$, with replacement, it is equivalent to sampling from $\\hat F_n$. \n\n## The Bootstrap Method\n\nThe Bootstrap Method is commonly used to obtain the standard error and or confidence limits of an estimator. By repeatedly sampling from $\\hat F_n$, the sampling distribution of any estimator can be approximated. This is advantageous from standard mathematical models which imposes a distribution on $F$, which may be completely inaccurate. The only assumption being made is that $\\hat F_n$ is close the true distribution function $F$.  \n\n### Algorithm\n\nLet $\\boldsymbol X = (X_1, X_2, \\ldots, X_n)$ be a random sample from a distribution $F$. For an estimator $T(\\cdot)$: \n\n1.  Draw a sample $\\boldsymbol X^*_b$ of size $n$, with replacement, from the original data $\\boldsymbol X$.\n2.  Compute the bootstrap replicate statistic $T*_b = T(\\boldsymbol X^*_b)$, where $T(\\cdot)$ is the function that computes the statistic of interest.\n3.  Repeat steps 1-2 $B$ times to obtain $B$ bootstrap replicates $T^*{T*_1, T*_2, ..., T*_B}$.\n\n\nThe computed statistics from $B$ samples are the empirical bootstrap distribution of the estimator, $T(\\boldsymbol X)$. This can be used to compute the standard error, bias, and confidence interval of the estimator $T(\\boldsymbol X)$. The number or replicates needed is open to discussion; however, research has shown $B=200$ to suffiece. Larger $B$ may be needed for confidence limit estimation. Another rule of thumb is having $B=n$; however, this may be unfeasible for extremely large samples or computationally intensive tasks.\n\n### Standard Error Estimation\n\nThe bootstrap-based standard error of an estimator is shown to provide an unbiased estimate of the true standard error. We can compute the standard eror using the following formula:\n\n$$\n\\hat{se}\\left\\{T(\\boldsymbol X)\\right\\} = \\sqrt{\\frac{1}{B-1}\\sum^B_{i=1}(T^*_i-\\bar T^*)^2}\n$$\nwhere $\\bar T^* = \\frac{1}{B}\\sum^B_{i=1}T^*_i$.\n\n\n### Bias Estimation\n\nThe bootstrap-based bias estimate can be computed by the following formula:\n\n$$\n\\widehat{bias}\\left\\{T(\\boldsymbol X)\\right\\} = \\bar T^* -  T(X)\n$$\n\nwhere $\\bar T^* = \\frac{1}{B}\\sum^B_{i=1}T^*_i$ is the mean estimate of the bootstrap samples and $T(X)$ is computed statistic from the data.\n\n### Confidence Limits Estimation\n\nThe confidence limits of a parameter can be estimated by using the percentiles of the bootstrap replicates. The $(1-\\alpha) 100 \\%$ bootstrap confidence interval can be represented as:\n\n$$\n(T^*_{\\alpha/2},\\ T^*_{1-\\alpha/2})\n$$\nwhere $T^*_{\\alpha/2}$ with $\\alpha/2$ quantile and $T^*_{1-\\alpha/2}$ quantile of the bootstrap replicates.\n\n\n### Limitation to Boostrap Methods\n\nLet's say we randomly sample 5 data points from a Poisson Distribution with a rate of 5^[Note: The `set.seed` function ensures that the same random sample will be generated.]:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nx <- rpois(5, 1.5)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 3 4 1 3 2\n```\n\n\n:::\n:::\n\n\n\nIf we were to use this sample and generate bootstrap estimates, we will obtain inaccurate results. This is because the empirical distribution function is a poor estimate of the true distribution function. One reason being that the $P(X = 0) = 0.2231$, and our sample does not have any 0 values. Any bootstrap samples produced will never carry that information. This is why a large sample is needed so the sample space can be thoroughly explored.\n\n## Examples\n\nThe examples below illustrate how to compute the bootstrap standard errors and confidence limits in a regression setting.\n\n### Linear Regression\n\nThe `mtcars` data set contains information on cars from 1974 *Motor Trend* US Magazine. Fitting a linear regression model between the variable `mpg` and `wt`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(mpg ~ wt, mtcars) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = mpg ~ wt, data = mtcars)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.5432 -2.3647 -0.1252  1.4096  6.8727 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  37.2851     1.8776  19.858  < 2e-16 ***\n#> wt           -5.3445     0.5591  -9.559 1.29e-10 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 3.046 on 30 degrees of freedom\n#> Multiple R-squared:  0.7528,\tAdjusted R-squared:  0.7446 \n#> F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10\n```\n\n\n:::\n\n```{.r .cell-code}\nlm(mpg ~ wt, mtcars) |> confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                 2.5 %    97.5 %\n#> (Intercept) 33.450500 41.119753\n#> wt          -6.486308 -4.202635\n```\n\n\n:::\n:::\n\n\nWe can see that the estimated model between the 2 variables is $\\widehat{mpg} = 37.285 - 5.345 wt$. The standard error, based on the normal distribution, for the coefficient of `wt` is 0.5591. The 95% confidence interval for the coefficient of `wt` is (-6.486, -4.203)^[Note: The residual analysis may suggest that the linear regression model is not appropriate.].\n\nTo obtain the bootstrap-based standard error and 95% confidence interval, we will need to sample data points in the data set, with replacement. The user created function below will sample data points with replacement^[Note: You will need to have the `dplyr` function installed.]:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresample <- function(df){\n  dplyr::slice_sample(df, n = nrow(df), replace = T )\n}\n```\n:::\n\n\n\nUsing the `resample`, we can get a bootstrap sample:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1 <- resample(mtcars)\nb1\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"mpg\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cyl\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"disp\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"hp\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"drat\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"wt\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"qsec\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"vs\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"am\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gear\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carb\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"21.4\",\"2\":\"6\",\"3\":\"258.0\",\"4\":\"110\",\"5\":\"3.08\",\"6\":\"3.215\",\"7\":\"19.44\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Hornet 4 Drive...1\"},{\"1\":\"32.4\",\"2\":\"4\",\"3\":\"78.7\",\"4\":\"66\",\"5\":\"4.08\",\"6\":\"2.200\",\"7\":\"19.47\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Fiat 128...2\"},{\"1\":\"27.3\",\"2\":\"4\",\"3\":\"79.0\",\"4\":\"66\",\"5\":\"4.08\",\"6\":\"1.935\",\"7\":\"18.90\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Fiat X1-9...3\"},{\"1\":\"14.7\",\"2\":\"8\",\"3\":\"440.0\",\"4\":\"230\",\"5\":\"3.23\",\"6\":\"5.345\",\"7\":\"17.42\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"4\",\"_rn_\":\"Chrysler Imperial\"},{\"1\":\"21.4\",\"2\":\"4\",\"3\":\"121.0\",\"4\":\"109\",\"5\":\"4.11\",\"6\":\"2.780\",\"7\":\"18.60\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"2\",\"_rn_\":\"Volvo 142E\"},{\"1\":\"10.4\",\"2\":\"8\",\"3\":\"472.0\",\"4\":\"205\",\"5\":\"2.93\",\"6\":\"5.250\",\"7\":\"17.98\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"4\",\"_rn_\":\"Cadillac Fleetwood...6\"},{\"1\":\"13.3\",\"2\":\"8\",\"3\":\"350.0\",\"4\":\"245\",\"5\":\"3.73\",\"6\":\"3.840\",\"7\":\"15.41\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"4\",\"_rn_\":\"Camaro Z28\"},{\"1\":\"14.3\",\"2\":\"8\",\"3\":\"360.0\",\"4\":\"245\",\"5\":\"3.21\",\"6\":\"3.570\",\"7\":\"15.84\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"4\",\"_rn_\":\"Duster 360\"},{\"1\":\"21.4\",\"2\":\"6\",\"3\":\"258.0\",\"4\":\"110\",\"5\":\"3.08\",\"6\":\"3.215\",\"7\":\"19.44\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Hornet 4 Drive...9\"},{\"1\":\"19.2\",\"2\":\"8\",\"3\":\"400.0\",\"4\":\"175\",\"5\":\"3.08\",\"6\":\"3.845\",\"7\":\"17.05\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Pontiac Firebird...10\"},{\"1\":\"18.7\",\"2\":\"8\",\"3\":\"360.0\",\"4\":\"175\",\"5\":\"3.15\",\"6\":\"3.440\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Hornet Sportabout...11\"},{\"1\":\"15.2\",\"2\":\"8\",\"3\":\"275.8\",\"4\":\"180\",\"5\":\"3.07\",\"6\":\"3.780\",\"7\":\"18.00\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"3\",\"_rn_\":\"Merc 450SLC\"},{\"1\":\"33.9\",\"2\":\"4\",\"3\":\"71.1\",\"4\":\"65\",\"5\":\"4.22\",\"6\":\"1.835\",\"7\":\"19.90\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Toyota Corolla...13\"},{\"1\":\"27.3\",\"2\":\"4\",\"3\":\"79.0\",\"4\":\"66\",\"5\":\"4.08\",\"6\":\"1.935\",\"7\":\"18.90\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Fiat X1-9...14\"},{\"1\":\"32.4\",\"2\":\"4\",\"3\":\"78.7\",\"4\":\"66\",\"5\":\"4.08\",\"6\":\"2.200\",\"7\":\"19.47\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Fiat 128...15\"},{\"1\":\"10.4\",\"2\":\"8\",\"3\":\"472.0\",\"4\":\"205\",\"5\":\"2.93\",\"6\":\"5.250\",\"7\":\"17.98\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"4\",\"_rn_\":\"Cadillac Fleetwood...16\"},{\"1\":\"22.8\",\"2\":\"4\",\"3\":\"108.0\",\"4\":\"93\",\"5\":\"3.85\",\"6\":\"2.320\",\"7\":\"18.61\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Datsun 710...17\"},{\"1\":\"22.8\",\"2\":\"4\",\"3\":\"140.8\",\"4\":\"95\",\"5\":\"3.92\",\"6\":\"3.150\",\"7\":\"22.90\",\"8\":\"1\",\"9\":\"0\",\"10\":\"4\",\"11\":\"2\",\"_rn_\":\"Merc 230\"},{\"1\":\"19.2\",\"2\":\"8\",\"3\":\"400.0\",\"4\":\"175\",\"5\":\"3.08\",\"6\":\"3.845\",\"7\":\"17.05\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Pontiac Firebird...19\"},{\"1\":\"26.0\",\"2\":\"4\",\"3\":\"120.3\",\"4\":\"91\",\"5\":\"4.43\",\"6\":\"2.140\",\"7\":\"16.70\",\"8\":\"0\",\"9\":\"1\",\"10\":\"5\",\"11\":\"2\",\"_rn_\":\"Porsche 914-2\"},{\"1\":\"21.4\",\"2\":\"6\",\"3\":\"258.0\",\"4\":\"110\",\"5\":\"3.08\",\"6\":\"3.215\",\"7\":\"19.44\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Hornet 4 Drive...21\"},{\"1\":\"18.7\",\"2\":\"8\",\"3\":\"360.0\",\"4\":\"175\",\"5\":\"3.15\",\"6\":\"3.440\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Hornet Sportabout...22\"},{\"1\":\"15.0\",\"2\":\"8\",\"3\":\"301.0\",\"4\":\"335\",\"5\":\"3.54\",\"6\":\"3.570\",\"7\":\"14.60\",\"8\":\"0\",\"9\":\"1\",\"10\":\"5\",\"11\":\"8\",\"_rn_\":\"Maserati Bora\"},{\"1\":\"17.3\",\"2\":\"8\",\"3\":\"275.8\",\"4\":\"180\",\"5\":\"3.07\",\"6\":\"3.730\",\"7\":\"17.60\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"3\",\"_rn_\":\"Merc 450SL\"},{\"1\":\"18.7\",\"2\":\"8\",\"3\":\"360.0\",\"4\":\"175\",\"5\":\"3.15\",\"6\":\"3.440\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Hornet Sportabout...25\"},{\"1\":\"33.9\",\"2\":\"4\",\"3\":\"71.1\",\"4\":\"65\",\"5\":\"4.22\",\"6\":\"1.835\",\"7\":\"19.90\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Toyota Corolla...26\"},{\"1\":\"21.0\",\"2\":\"6\",\"3\":\"160.0\",\"4\":\"110\",\"5\":\"3.90\",\"6\":\"2.875\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"1\",\"10\":\"4\",\"11\":\"4\",\"_rn_\":\"Mazda RX4 Wag\"},{\"1\":\"30.4\",\"2\":\"4\",\"3\":\"95.1\",\"4\":\"113\",\"5\":\"3.77\",\"6\":\"1.513\",\"7\":\"16.90\",\"8\":\"1\",\"9\":\"1\",\"10\":\"5\",\"11\":\"2\",\"_rn_\":\"Lotus Europa\"},{\"1\":\"24.4\",\"2\":\"4\",\"3\":\"146.7\",\"4\":\"62\",\"5\":\"3.69\",\"6\":\"3.190\",\"7\":\"20.00\",\"8\":\"1\",\"9\":\"0\",\"10\":\"4\",\"11\":\"2\",\"_rn_\":\"Merc 240D\"},{\"1\":\"22.8\",\"2\":\"4\",\"3\":\"108.0\",\"4\":\"93\",\"5\":\"3.85\",\"6\":\"2.320\",\"7\":\"18.61\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Datsun 710...30\"},{\"1\":\"27.3\",\"2\":\"4\",\"3\":\"79.0\",\"4\":\"66\",\"5\":\"4.08\",\"6\":\"1.935\",\"7\":\"18.90\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Fiat X1-9...31\"},{\"1\":\"21.0\",\"2\":\"6\",\"3\":\"160.0\",\"4\":\"110\",\"5\":\"3.90\",\"6\":\"2.620\",\"7\":\"16.46\",\"8\":\"0\",\"9\":\"1\",\"10\":\"4\",\"11\":\"4\",\"_rn_\":\"Mazda RX4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\nNotice that some data points are repeated. We will then construct 10,000 bootstrap samples:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboots <- lapply(1:10000, \\(x) resample(mtcars))\n```\n:::\n\n\n\nThe object `boots` is a list, with each element contain a boot replicate data set. Now we will, apply the `lm` function for each data set in `boots`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboots_lm <- lapply(boots, \\(x) lm(mpg ~ wt, x))\n```\n:::\n\n\n\nLastly, we will extract the coefficient value for each replicate^[We will unlist the object to utilize a vector]:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboots_wt <- lapply(boots_lm, \\(x) coef(x)[\"wt\"]) |> unlist()\n```\n:::\n\n\n\nLet's visualize the distribution for the coefficient of `wt`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(x = boots_wt) |> \n  ggplot(aes(x)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](bootstrapping_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\nThe plot indicate that the coefficient for `wt` may not be symmetrical. The standard error can be obtained by applying the `sd` function to `boots_wt`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(boots_wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.7046252\n```\n\n\n:::\n:::\n\n\n\nThe bootstrap-based standard error is 0.71. This is different from the normal-based standard error of 0.55. The 95% confidence interval of the coefficient of `wt` cna be obtained by using the `quantile` function and setting `probs = c(0.025, 0.975)`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(boots_wt, probs = c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>      2.5%     97.5% \n#> -6.953420 -4.130759\n```\n\n\n:::\n:::\n\n\n\nThe bootstrap-based 95% confidence interval is (-6.973, -4.164), which is slightly wider than the mathematical-based 95% confidence interval: (-6.486, -4.203).",
    "supporting": [
      "bootstrapping_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}